"""add response score to training reports

Revision ID: 6aa62836a202
Revises: a57df538859c
Create Date: 2026-08-25 05:39:41.504414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa62836a202'
down_revision: Union[str, Sequence[str], None] = 'a57df538859c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_reports', sa.Column('score', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_reports', 'score')
    # ### end Alembic commands ###
