"""create training tables

Revision ID: 9523413ee830
Revises: 
Create Date: 2026-08-24 09:04:51.640870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9523413ee830'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('phone_number_masked', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_phone_number'), 'participants', ['phone_number'], unique=True)
    op.create_table('transcript_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clawops_call_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clawops_call_id', 'event_type', name='uq_transcript_call_event')
    )
    op.create_index(op.f('ix_transcript_events_clawops_call_id'), 'transcript_events', ['clawops_call_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('current_training_type', sa.String(length=20), nullable=False),
    sa.Column('call_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_participant_id'), 'training_sessions', ['participant_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('clawops_call_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_clawops_call_id'), 'calls', ['clawops_call_id'], unique=True)
    op.create_index(op.f('ix_calls_session_id'), 'calls', ['session_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('privacy_agreed', sa.Boolean(), nullable=False),
    sa.Column('surprise_call_agreed', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_session_id'), 'consents', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consents_session_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_calls_session_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_clawops_call_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_training_sessions_participant_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_transcript_events_clawops_call_id'), table_name='transcript_events')
    op.drop_table('transcript_events')
    op.drop_index(op.f('ix_participants_phone_number'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
