"""add transcript turns and training reports

Revision ID: a57df538859c
Revises: c81e76c4b1a2
Create Date: 2026-08-25 00:36:17.672283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57df538859c'
down_revision: Union[str, Sequence[str], None] = 'c81e76c4b1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('suspected', sa.Boolean(), nullable=False),
    sa.Column('gave_name', sa.Boolean(), nullable=False),
    sa.Column('tried_hangup', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('coaching', sa.Text(), nullable=False),
    sa.Column('risk_behaviors', sa.JSON(), nullable=False),
    sa.Column('defense_behaviors', sa.JSON(), nullable=False),
    sa.Column('clawops_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'source', name='uq_report_session_source')
    )
    op.create_index(op.f('ix_training_reports_call_id'), 'training_reports', ['call_id'], unique=False)
    op.create_index(op.f('ix_training_reports_session_id'), 'training_reports', ['session_id'], unique=False)
    op.create_table('transcript_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'source', 'sequence', name='uq_turn_sequence')
    )
    op.create_index(op.f('ix_transcript_turns_call_id'), 'transcript_turns', ['call_id'], unique=False)
    op.create_index(op.f('ix_transcript_turns_session_id'), 'transcript_turns', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_turns_session_id'), table_name='transcript_turns')
    op.drop_index(op.f('ix_transcript_turns_call_id'), table_name='transcript_turns')
    op.drop_table('transcript_turns')
    op.drop_index(op.f('ix_training_reports_session_id'), table_name='training_reports')
    op.drop_index(op.f('ix_training_reports_call_id'), table_name='training_reports')
    op.drop_table('training_reports')
    # ### end Alembic commands ###
